// <auto-generated />
namespace BankAccountNet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class menu_control : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(menu_control));
        
        string IMigrationMetadata.Id
        {
            get { return "201808220055013_menu_control"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
