// <auto-generated />
namespace BankAccountNet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class fix_term : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix_term));
        
        string IMigrationMetadata.Id
        {
            get { return "201808220044330_fix_term"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
